#!/bin/bash

version=$(node -p "require('./package.json').version")
echo "<?php define('vikalpsangam_VERSION', '$version');" >| version.php
echo "\$theme-version: \"$version\";" >| sass/_version.scss
