<?php


// Primary
function megamenu_add_theme_vikalpsangam_org_theme_menu_1624823357($themes) {
    $themes["vikalpsangam_org_theme_menu_1624823357"] = array(
        'title' => 'Vikalpsangam_org Theme Menu',
        'container_background_from' => 'rgb(248, 249, 250)',
        'container_background_to' => 'rgb(248, 249, 250)',
        'menu_item_align' => 'center',
        'menu_item_background_hover_from' => 'rgb(158, 51, 46)',
        'menu_item_background_hover_to' => 'rgb(158, 51, 46)',
        'menu_item_link_font_size' => '18px',
        'menu_item_link_height' => '54px',
        'menu_item_link_color' => 'rgb(158, 51, 46)',
        'menu_item_link_weight' => 'bold',
        'menu_item_link_text_transform' => 'uppercase',
        'menu_item_link_text_align' => 'center',
        'menu_item_link_weight_hover' => 'bold',
        'panel_background_from' => 'rgb(255, 255, 255)',
        'panel_background_to' => 'rgb(255, 255, 255)',
        'panel_inner_width' => '1024px',
        'panel_border_color' => 'rgb(158, 51, 46)',
        'panel_border_bottom' => '1px',
        'panel_header_color' => 'rgb(117, 14, 9)',
        'panel_header_text_transform' => 'none',
        'panel_header_border_color' => 'rgb(210, 210, 210)',
        'panel_header_border_color_hover' => 'rgb(210, 210, 210)',
        'panel_header_border_bottom' => '1px',
        'panel_padding_top' => '2px',
        'panel_padding_bottom' => '8px',
        'panel_widget_padding_top' => '2px',
        'panel_widget_padding_bottom' => '2px',
        'panel_font_size' => '14px',
        'panel_font_color' => 'rgb(158, 51, 46)',
        'panel_font_family' => 'inherit',
        'panel_second_level_font_color' => 'rgb(158, 51, 46)',
        'panel_second_level_font_color_hover' => 'rgb(158, 51, 46)',
        'panel_second_level_text_transform' => 'none',
        'panel_second_level_font' => 'inherit',
        'panel_second_level_font_size' => '14px',
        'panel_second_level_font_weight' => 'normal',
        'panel_second_level_font_weight_hover' => 'normal',
        'panel_second_level_text_decoration' => 'none',
        'panel_second_level_text_decoration_hover' => 'none',
        'panel_second_level_padding_top' => '5px',
        'panel_second_level_padding_bottom' => '5px',
        'panel_third_level_font_color' => 'rgb(158, 51, 46)',
        'panel_third_level_font_color_hover' => 'rgb(85, 85, 85)',
        'panel_third_level_font' => 'Arial, Helvetica, sans-serif',
        'panel_third_level_font_size' => '14px',
        'panel_third_level_border_color' => 'rgba(255, 255, 255, 0.1)',
        'flyout_menu_background_from' => 'rgb(255, 255, 255)',
        'flyout_menu_background_to' => 'rgb(255, 255, 255)',
        'flyout_link_size' => '14px',
        'flyout_link_color' => 'rgb(85, 85, 85)',
        'flyout_link_color_hover' => 'rgb(85, 85, 85)',
        'flyout_link_family' => 'inherit',
        'shadow' => 'on',
        'toggle_background_from' => 'rgb(248, 249, 250)',
        'toggle_background_to' => 'rgb(248, 249, 250)',
        'toggle_bar_height' => '54px',
        'mobile_background_from' => 'rgb(255, 255, 255)',
        'mobile_background_to' => 'rgb(255, 255, 255)',
        'mobile_menu_item_link_font_size' => '18px',
        'mobile_menu_item_link_color' => 'rgb(158, 51, 46)',
        'mobile_menu_item_link_text_align' => 'left',
        'mobile_menu_item_link_color_hover' => '#ffffff',
        'mobile_menu_item_background_hover_from' => 'rgb(158, 51, 46)',
        'mobile_menu_item_background_hover_to' => 'rgb(158, 51, 46)',
        'custom_css' => '/** Push menu onto new line **/ 
#{$wrap} { 
    clear: both; 
}',
    );
    return $themes;
}
add_filter("megamenu_themes", "megamenu_add_theme_vikalpsangam_org_theme_menu_1624823357");

// Secondary
function megamenu_add_theme_vikalpsangam_org_theme_menu_secondary_1624823414($themes) {
    $themes["vikalpsangam_org_theme_menu_secondary_1624823414"] = array(
        'title' => 'Vikalpsangam_org Theme Menu Secondary',
        'container_background_from' => 'rgb(99, 32, 29)',
        'container_background_to' => 'rgb(99, 32, 29)',
        'menu_item_align' => 'center',
        'menu_item_background_hover_from' => 'rgb(255, 255, 255)',
        'menu_item_background_hover_to' => 'rgb(255, 255, 255)',
        'menu_item_link_font_size' => '18px',
        'menu_item_link_height' => '54px',
        'menu_item_link_color' => 'rgb(255, 255, 255)',
        'menu_item_link_color_hover' => 'rgb(158, 51, 46)',
        'menu_item_border_color' => 'rgb(255, 255, 255)',
        'panel_font_size' => '14px',
        'panel_font_color' => '#666',
        'panel_font_family' => 'inherit',
        'panel_second_level_font_color' => '#555',
        'panel_second_level_font_color_hover' => '#555',
        'panel_second_level_text_transform' => 'uppercase',
        'panel_second_level_font' => 'inherit',
        'panel_second_level_font_size' => '16px',
        'panel_second_level_font_weight' => 'bold',
        'panel_second_level_font_weight_hover' => 'bold',
        'panel_second_level_text_decoration' => 'none',
        'panel_second_level_text_decoration_hover' => 'none',
        'panel_third_level_font_color' => '#666',
        'panel_third_level_font_color_hover' => '#666',
        'panel_third_level_font' => 'inherit',
        'panel_third_level_font_size' => '14px',
        'flyout_menu_background_from' => 'rgb(255, 255, 255)',
        'flyout_menu_background_to' => 'rgb(255, 255, 255)',
        'flyout_link_weight' => 'bold',
        'flyout_link_weight_hover' => 'bold',
        'flyout_background_from' => 'rgb(255, 255, 255)',
        'flyout_background_to' => 'rgb(255, 255, 255)',
        'flyout_background_hover_from' => 'rgb(255, 255, 255)',
        'flyout_background_hover_to' => 'rgb(255, 255, 255)',
        'flyout_link_size' => '16px',
        'flyout_link_color' => 'rgb(158, 51, 46)',
        'flyout_link_color_hover' => 'rgb(124, 34, 34)',
        'flyout_link_family' => 'inherit',
        'z_index' => '6000',
        'toggle_background_from' => 'rgb(248, 249, 250)',
        'toggle_background_to' => 'rgb(248, 249, 250)',
        'toggle_bar_height' => '54px',
        'mobile_background_from' => 'rgb(255, 255, 255)',
        'mobile_background_to' => 'rgb(255, 255, 255)',
        'mobile_menu_item_link_font_size' => '14px',
        'mobile_menu_item_link_color' => 'rgb(158, 51, 46)',
        'mobile_menu_item_link_text_align' => 'left',
        'mobile_menu_item_link_color_hover' => '#ffffff',
        'mobile_menu_item_background_hover_from' => '#333',
        'mobile_menu_item_background_hover_to' => '#333',
        'custom_css' => '/** Push menu onto new line **/ 
#{$wrap} { 
    clear: both; 
}',
    );
    return $themes;
}
add_filter("megamenu_themes", "megamenu_add_theme_vikalpsangam_org_theme_menu_secondary_1624823414");