name: Build and deploy from dev branch
on:
  push:
    branches:
      - 'develop-*'
    paths-ignore:
        - '.github/**'
jobs:
  deploy:
    environment: 
      name: dev
      url: https://dev.vikalpsangam.org
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    
    - uses: php-actions/composer@v2
      with:
        dev: no

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: "npm install"
      run: npm ci

    - name: "Serialise version"
      run: | 
        version=$(node -p "require('./package.json').version")
        echo "<?php define('vikalpsangam_VERSION', '$version');" >| version.php
        echo "\$theme-version: \"$version\";" >| _version.scss

    - name: "Compile scss -> css"
      run: npm run build:scss

    - name: "Compile rtl css"
      run: npm run build:scss-rtl
    
    - name: "Create theme bundle"
      run: npm run bundle

    - name: Upload theme bundle
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: vikalpsangam.org.zip
        target: /tmp/vikalpsangam.org.zip

    - name: Install plugin using Wordpress cli over ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo wp theme install /tmp/vikalpsangam.org.zip \
            --activate \
            --allow-root \
            --path=${{ secrets.WORDPRESS_PATH }} \
            --force