name: build
on:
  push:
    branches:
      - 'master'
    paths-ignore:
        - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: php-actions/composer@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: "Lint php"
      run: composer lint:php

    - name: "npm install"
      run: npm ci

    - name: "Lint scss"
      run: npm run lint:scss

    - name: "Lint js"
      run: npm run lint:js

    - name: "Increment Version"
      id: "version-bump"
      run: | 
        git config --global user.email ${{ github.actor }}
        git config --global user.name ${{ github.actor }}
        npm version patch
        version=$(node -p "require('./package.json').version")
        echo "<?php define('vikalpsangam_VERSION', '$version');" >| version.php
        echo "\$theme-version: \"$version\";" >| _version.scss
        echo "::set-output name=version::$version"

    - name: "Compile scss -> css"
      run: npm run build:scss

    - name: "Compile rtl css"
      run: npm run build:scss-rtl

    - name: "Create theme bundle"
      run: npm run bundle
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload theme package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vikalpsangam.org.zip
        asset_name: vikalpsangam.org-${{ steps.version-bump.outputs.version }}.zip
        tag: ${{ steps.version-bump.outputs.version }}
        overwrite: true
        body: "Wordpress Theme for vikalpsangam.org. Version ${{ steps.version-bump.outputs.version }}"
