name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: php-actions/composer@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    
    - run: composer lint:wpcs
    - run: composer lint:php

    - run: npm ci
    - run: npm run lint:scss
    - run: npm run compile:css

    - name: Deploy Plugins and Themes to WP Server
      uses: appleboy/scp-action@master
      with:
        username: root
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        source: "wp-content"
        target: "/var/www/html"
        port: 22
