name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        username: root
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        source: "wp-content"
        target: "/var/www/html"
        port: 22
