name: CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: php-actions/composer@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: "Lint php"
      run: composer lint:php

    - name: "npm install"
      run: npm ci

    - name: "Lint scss"
      run: npm run lint:scss

    - name: "Compile scss -> css"
      run: npm run build:scss

    - name: "Compile rtl css"
      run: npm run build:scss-rtl

    - name: "Lint js"
      run: npm run lint:js

    - name: "Create theme bundle"
      run: npm run bundle

    - name: Deploy Plugins and Themes to WP Server
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.DEPLOYMENT_USER }}
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        source: "vikalpsangam.zip"
        target: "/tmp"
        port: 22
    
    - name: Upload theme package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vikalpsangam.zip
        asset_name: vikalpsangam.org-${{ github.event.release.tag_name }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Wordpress Theme for vikalpsangam.org. Version  ${{ github.event.release.tag_name }}"
      
    - name: Install theme using Wordpress cli over ssh
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.DEPLOYMENT_USER }}
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        port: 22
        script: |
          sudo wp theme install /tmp/vikalpsangam.zip \
            --activate \
            --allow-root \
            --path=/var/www/html \
            --force

    - name: Update Wordpress settings
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.DEPLOYMENT_USER }}
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        port: 22
        script: |
          wp --path=/var/www/html option update home "https://dev.vikalpsangam.org"
          wp --path=/var/www/html option update siteurl "https://dev.vikalpsangam.org"	
          wp --path=/var/www/html option set "blogname" "Vikalp Sangam"
          wp --path=/var/www/html rewrite structure "/article/%postname%/" --tag-base="/tag"
          wp --path=/var/www/html plugin install \
            advanced-custom-fields \
            redirection \
            longer-permalinks \
            categories-images \
            export-import-menus \
          --activate
          
